# ============================================================
# IntelliWealth – Redis ConfigMap
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: intelliwealth
  labels:
    app: redis
    app.kubernetes.io/part-of: intelliwealth
data:
  redis.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    tcp-keepalive 300
    timeout 0
    save 900 1
    save 300 10
    save 60 10000
