# ============================================================
# IntelliWealth – Frontend Service
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: intelliwealth
  labels:
    app: frontend
    app.kubernetes.io/part-of: intelliwealth
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
