# ============================================================
# IntelliWealth – Portfolio Service
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: intelliwealth
  labels:
    app: portfolio-service
    app.kubernetes.io/part-of: intelliwealth
    app.kubernetes.io/component: backend
spec:
  selector:
    app: portfolio-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
